// <auto-generated />
using System;
using ForumWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumWebsite.Migrations
{
    [DbContext(typeof(MyDBContextApplication))]
    [Migration("20251106114126_database01")]
    partial class database01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForumWebsite.Models.Activity.BookmarkModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThreadID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ThreadID");

                    b.HasIndex("UserID");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("ForumWebsite.Models.Activity.LikeModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThreadID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ThreadID");

                    b.HasIndex("UserID");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("ForumWebsite.Models.Activity.ReportModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<int>("ThreadID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StatusID");

                    b.HasIndex("ThreadID");

                    b.HasIndex("UserID");

                    b.ToTable("ReportModels");
                });

            modelBuilder.Entity("ForumWebsite.Models.Reply.ImageModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublicID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReplyID")
                        .HasColumnType("int");

                    b.Property<int?>("ThreadID")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ReplyID")
                        .IsUnique()
                        .HasFilter("[ReplyID] IS NOT NULL");

                    b.HasIndex("ThreadID")
                        .IsUnique()
                        .HasFilter("[ThreadID] IS NOT NULL");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("ForumWebsite.Models.Reply.ReplyModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentReplyID")
                        .HasColumnType("int");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<int>("ThreadID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ParentReplyID");

                    b.HasIndex("StatusID");

                    b.HasIndex("ThreadID");

                    b.HasIndex("UserID");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("ForumWebsite.Models.Thread.CategoryModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ForumWebsite.Models.Thread.StatusModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("ForumWebsite.Models.Thread.ThreadModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ReplyLimit")
                        .HasColumnType("int");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("StatusID");

                    b.HasIndex("UserID");

                    b.ToTable("Threads");
                });

            modelBuilder.Entity("ForumWebsite.Models.User.UserActivityModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ReplyID")
                        .HasColumnType("int");

                    b.Property<int?>("ReplyModelID")
                        .HasColumnType("int");

                    b.Property<int?>("ThreadID")
                        .HasColumnType("int");

                    b.Property<int?>("ThreadModelID")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<int?>("UserModelID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ReplyID");

                    b.HasIndex("ReplyModelID");

                    b.HasIndex("ThreadID");

                    b.HasIndex("ThreadModelID");

                    b.HasIndex("UserID");

                    b.HasIndex("UserModelID");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("ForumWebsite.Models.User.UserModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("StatusID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ForumWebsite.Models.Activity.BookmarkModel", b =>
                {
                    b.HasOne("ForumWebsite.Models.Thread.ThreadModel", "Thread")
                        .WithMany("Bookmarks")
                        .HasForeignKey("ThreadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForumWebsite.Models.User.UserModel", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Thread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumWebsite.Models.Activity.LikeModel", b =>
                {
                    b.HasOne("ForumWebsite.Models.Thread.ThreadModel", "Thread")
                        .WithMany("Likes")
                        .HasForeignKey("ThreadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForumWebsite.Models.User.UserModel", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Thread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumWebsite.Models.Activity.ReportModel", b =>
                {
                    b.HasOne("ForumWebsite.Models.Thread.StatusModel", "Status")
                        .WithMany("Reports")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForumWebsite.Models.Thread.ThreadModel", "Thread")
                        .WithMany("Reports")
                        .HasForeignKey("ThreadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForumWebsite.Models.User.UserModel", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Thread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumWebsite.Models.Reply.ImageModel", b =>
                {
                    b.HasOne("ForumWebsite.Models.Reply.ReplyModel", "Reply")
                        .WithOne("Image")
                        .HasForeignKey("ForumWebsite.Models.Reply.ImageModel", "ReplyID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ForumWebsite.Models.Thread.ThreadModel", "Thread")
                        .WithOne("Image")
                        .HasForeignKey("ForumWebsite.Models.Reply.ImageModel", "ThreadID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Reply");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("ForumWebsite.Models.Reply.ReplyModel", b =>
                {
                    b.HasOne("ForumWebsite.Models.Reply.ReplyModel", "ParentReply")
                        .WithMany("ChildReplies")
                        .HasForeignKey("ParentReplyID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ForumWebsite.Models.Thread.StatusModel", "Status")
                        .WithMany("Replies")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForumWebsite.Models.Thread.ThreadModel", "Thread")
                        .WithMany("Replies")
                        .HasForeignKey("ThreadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForumWebsite.Models.User.UserModel", "User")
                        .WithMany("Replies")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentReply");

                    b.Navigation("Status");

                    b.Navigation("Thread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumWebsite.Models.Thread.ThreadModel", b =>
                {
                    b.HasOne("ForumWebsite.Models.Thread.CategoryModel", "Category")
                        .WithMany("Threads")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForumWebsite.Models.Thread.StatusModel", "Status")
                        .WithMany("Threads")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForumWebsite.Models.User.UserModel", "User")
                        .WithMany("Threads")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumWebsite.Models.User.UserActivityModel", b =>
                {
                    b.HasOne("ForumWebsite.Models.Reply.ReplyModel", "Reply")
                        .WithMany()
                        .HasForeignKey("ReplyID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ForumWebsite.Models.Reply.ReplyModel", null)
                        .WithMany("UserActivites")
                        .HasForeignKey("ReplyModelID");

                    b.HasOne("ForumWebsite.Models.Thread.ThreadModel", "Thread")
                        .WithMany()
                        .HasForeignKey("ThreadID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ForumWebsite.Models.Thread.ThreadModel", null)
                        .WithMany("UserActivites")
                        .HasForeignKey("ThreadModelID");

                    b.HasOne("ForumWebsite.Models.User.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ForumWebsite.Models.User.UserModel", null)
                        .WithMany("UserActivities")
                        .HasForeignKey("UserModelID");

                    b.Navigation("Reply");

                    b.Navigation("Thread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForumWebsite.Models.User.UserModel", b =>
                {
                    b.HasOne("ForumWebsite.Models.Thread.StatusModel", "Status")
                        .WithMany("Users")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ForumWebsite.Models.Reply.ReplyModel", b =>
                {
                    b.Navigation("ChildReplies");

                    b.Navigation("Image");

                    b.Navigation("UserActivites");
                });

            modelBuilder.Entity("ForumWebsite.Models.Thread.CategoryModel", b =>
                {
                    b.Navigation("Threads");
                });

            modelBuilder.Entity("ForumWebsite.Models.Thread.StatusModel", b =>
                {
                    b.Navigation("Replies");

                    b.Navigation("Reports");

                    b.Navigation("Threads");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ForumWebsite.Models.Thread.ThreadModel", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Image");

                    b.Navigation("Likes");

                    b.Navigation("Replies");

                    b.Navigation("Reports");

                    b.Navigation("UserActivites");
                });

            modelBuilder.Entity("ForumWebsite.Models.User.UserModel", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Likes");

                    b.Navigation("Replies");

                    b.Navigation("Reports");

                    b.Navigation("Threads");

                    b.Navigation("UserActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
